### ISSUE TITLE
How do I test signing against staging and dev AMO?

### ISSUE THREAD

**Issue by mpeteuil** [kewisch/action-web-ext#11]
In the README it mentions:
>Changing apiUrlPrefix will allow you to submit to addons.thunderbird.net or using the staging/dev instance.

I found the URLs for those instances in the [Github addons-server repo](https://github.com/mozilla/addons-server) and [related docs](https://addons-server.readthedocs.io/en/latest/topics/api/index.html#external-api), but have had a hard time trying to find out how to use those staging/dev instances for testing add-on signing. I was able to create an AMO account on the staging instance, but I don't seem to be able to generate API keys there since there's a confirmation email process but the staging environment doesn't send out emails (from what I can tell). I get the following message from https://addons.allizom.org/en-US/developers/addon/api/key/

>A confirmation link will be sent to your email address. After confirmation you will find your API keys on this page. 

Maybe this question is better posed somewhere else? I've found it difficult to find information about this generally available.

**Comment by kewisch** [comment]
Yeah I am not sure you can test on stage/dev, as you noted emails are disabled there. I mainly added this to support the Thunderbird use case.

**Comment by kewisch** [comment]
Confirmed with the team, email sending is disabled on dev/stage. You can of course test using a self-hosted add-on on prod, we would appreciate if you do so in reasonable intervals.
