### ISSUE TITLE
don't require auth token for linting

### ISSUE THREAD

**Issue by LennyPenny** [kewisch/action-web-ext#17]
would be cool if linting wouldn't require an auth token so it can run in PRs from people not part of the repo

**Comment by kewisch** [comment]
The action uses `GITHUB_TOKEN` from the env. What you could try is intentionally making it empty (e.g. setting an empty string via `env` in the action). I'm using the token to create check runs, so it will show one of those nice annotations. I'm not really sure why github doesn't allow this without auth.

Is this still an issue?

**Comment by groovecoder** [comment]
I'm trying something else now, so this isn't an issue for me anymore.

**Comment by kewisch** [comment]
On 3283e6644badba1e1f08710b8f7ed5ef1625a5b6 I changed it so the check run is ignored if permissions are not there. This way the action should still fail, and you only get the fancy check run if you have permissions.
