### ISSUE TITLE
Support for uploading sources

### ISSUE THREAD

**Issue by theowenyoung** [kewisch/action-web-ext#34]
Hi, thanks for the great action!

I'm using this for submit my extension, but firefox addon also need to submit source files when the dist files is minified.

are there any ways to figure out this?

**Comment by theowenyoung** [comment]
docs: https://extensionworkshop.com/documentation/publish/source-code-submission/

**Comment by kewisch** [comment]
See https://github.com/mozilla/sign-addon/issues/409 which I might need to do source code submission. There is a note that the unstable API supports it, though it would likely be a hack to directly call the API. Best case let's contribute to getting that issue fixed, then use sign-addon to submit sources.
