### ISSUE TITLE
'Lint' fails because of lack of token?

### ISSUE THREAD

**Issue by axelsimon** [kewisch/action-web-ext#36]
Hi,
I see the README [says](https://github.com/kewisch/action-web-ext#lint) that
> A token is not required for this action, though if GITHUB_TOKEN is in the environment, it will be used to create a check run.

but a [recent run](https://github.com/go-shiori/shiori-web-ext/actions/runs/4076779422) on this action on the Shiori web-ext failed with:
> call-lint / Lint Error: Parameter token or opts.auth is required

Between the fact the token is not supposed to be needed and that the GITHUB_TOKEN is added to the env in the setup job, i'm wondering if there isn't a bug somewhere.
Thanks!

**Comment by rugk** [comment]
Yeah, also see it failing, what is wrong here?

> Error: Error: Parameter token or opts.auth is required
Error: Parameter token or opts.auth is required
https://github.com/rugk/awesome-emoji-picker/actions/runs/5760316854/job/15616036996?pr=142

**Comment by rugk** [comment]
I don't know that code at all, but I saw there once was a solution that just added "dummyToken" there, I have no idea whether that works?

https://github.com/kewisch/action-web-ext/commit/3283e6644badba1e1f08710b8f7ed5ef1625a5b6#diff-de047e248d1853c5e41e476a8cb56eb5e6feb1e4e51eb2ee9c5061e838284860L13

Just not creating/calling `getOkctokit` does not seem like a solution given that this variable is used [at least two times](https://github.com/search?q=repo%3Akewisch/action-web-ext%20octokit&type=code). So I better let this do someone who knows this and can test it.
