### ISSUE TITLE
Warning: The `set-output` command is deprecated and will be disabled soon.

### ISSUE THREAD

**Issue by Diggsey** [kewisch/action-web-ext#37]
I'm getting this warning when using the action:

Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by 2zqa** [comment]
Can reproduce. I guess this is because of outdated packages?

**Comment by kewisch** [comment]
I'm not sure I need to do anything on this. The links says to upgrade `@actions/core` to 1.10.0 which I have done, so it should be ok and the message will just eventually go away?

**Comment by 2zqa** [comment]
I think people are still using [v1](https://github.com/kewisch/action-web-ext/tree/v1) as suggested by the readme, myself included. However even on [v1.2](https://github.com/kewisch/action-web-ext/tree/v1.2) the package.json still reads `^1.6.0`: https://github.com/kewisch/action-web-ext/blob/v1.2/package.json#L14C1-L14C31

Perhaps v1.3 is due?

**Comment by kewisch** [comment]
The guidance is to use v1, and not a specific version. Honestly I am just using main and v1, when it works I retag v1. I might just go ahead and delete the v1.n tags to not cause confusion.
