### ISSUE TITLE
Remove and ignore the `node_modules` directory

### ISSUE THREAD

**Issue by 2zqa** [kewisch/action-web-ext#42]
I noticed this repository has included the node_modules directory. This causes the git repository to be quite large in size. Are there any reasons for keeping it? I noticed the `.gitignore` file even explicitly allows it.

**Comment by kewisch** [comment]
I don't know if the recommendations have changed, but back in the early days of github actions, most docs said that node_modules needs to be added. Example still: https://docs.github.com/en/actions/creating-actions/creating-a-javascript-action#commit-tag-and-push-your-action-to-github . Granted that also says it can be problematic (without a why?), but I also don't want to start packing up javascript files.

Do you have any links on more current recommendations? Would love to better understand how things have changed.

**Comment by 2zqa** [comment]
Interesting to learn about that! I recently got into the development of GitHub actions and it seemed counter-intuitive to me. Primarily because the official typescript action template doesn't use it (https://github.com/actions/typescript-action), even though their simpler hello-world template does use it (https://github.com/actions/hello-world-javascript-action)

My other reasoning when I created this PR:

* It makes the repository rather large for something that can be generated using commands
* I read about the 'caching dependencies' documentation page on GitHub that talks about this, although to my surprise just now, it does not seem to cache node_modules after all[^1][^2] (https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows)
* When I was looking up online on whether to commit node_modules the general consensus seemed to be to not commit it, however I can see that a GitHub actions repository might be an exception.

I see now it is not as clear-cut as I initially thought. I'll leave it up to you on whether to include this PR or not.

[^1]: https://github.com/actions/cache/blob/main/examples.md#node---npm
[^2]: https://github.com/actions/setup-node#caching-global-packages-data

**Comment by kewisch** [comment]
I'm closing this one as it still seems to be the most current guidance to include node_modules. There is an alternative that uses @vercel/ncc to compile the result into one package, but that doesn't work with web-ext since it uses a dynamic import for config modules, which trips up ncc. I commented on one of the open issues there, I'd pick that up in case there is a viable solution.

**Comment by kewisch** [comment]
Leaving this here so I don't have to look it up next time: https://github.com/vercel/ncc/issues/935

**Comment by kewisch** [comment]
I think I was able to fix this via webpack instead of ncc. I'm a bit wary, but it appears to be working.
