### ISSUE TITLE
Expose timeout option for signing

### ISSUE THREAD

**Issue by mpeteuil** [kewisch/action-web-ext#9]
For me the signing times out after 2 minutes. What's odd about this is that the timeout in `sign-addon` was actually [changed from 2 minutes to 15 minutes a while back](https://github.com/mozilla/sign-addon/commit/47d4cf23d6ae3d5f0961e6c461b28836111fa5c9) and it's [still set to 15 minutes](https://github.com/mozilla/sign-addon/blob/830e970/src/amo-client.js#L162) as far as I can tell. In trying to find out if I could change it I was going to try providing an explicit timeout but I noticed that option is not exposed in this action. I was wondering how you'd feel about adding that as an option?

**Comment by kewisch** [comment]
Exposing that as an option works for me, I don't see why not. Glad to see others finding this action useful :)
